
default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind

before_script:
  - docker info

stages:
  - build
  - deploy

build_job:
  stage: build
  before_script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  script:
    - echo "Building the application..."
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

deploy_job:
  stage: deploy
  tags:
    - ec2-runner
  only:
    - feature/ci-cd
  script:
    - echo "Deploying the application..."
    - apk add gettext
    - envsubst < .dev/docker-compose.template.yml > docker-compose.yml
    - scp -i ${SSH_PRIVATE_KEY} docker-compose.yml ${REMOTE_USER}@${REMOTE_HOST}:~
    - ssh -i ${SSH_PRIVATE_KEY} ${REMOTE_USER}@${REMOTE_HOST} 'docker-compose up -d'
  environment:
    name: production
    url: http://${REMOTE_HOST}:8085