variables:
  CI_IMAGE_TAG: ${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}
default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind

before_script:
  - docker info

stages:
  - deploy

deploy_job:
  stage: deploy
  only:
    - feature/ci-cd
  script:
    - echo "Deploying the application..."
    - apk add gettext
    - ls -lah -R
    - envsubst < .dev/docker-compose.template.yml > docker-compose.yml
    - scp -i ${SSH_PRIVATE_KEY} docker-compose.yml ${REMOTE_USER}@${REMOTE_HOST}:~
    - ssh -i ${SSH_PRIVATE_KEY} ${REMOTE_USER}@${REMOTE_HOST} 'docker-compose up -d'
  environment:
    name: production
    url: http://${REMOTE_HOST}:8085