variables:
  CI_IMAGE_TAG: ${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}
default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind

before_script:
  - docker info

stages:
  - build
  - deploy

build_job:
  image: docker:20.10
  stage: build
  services:
    - docker:20.10-dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: '/certs'
    DOCKER_DRIVER: overlay2
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build
      --network host
      --tag $CI_REGISTRY_IMAGE:$CI_IMAGE_TAG
      .
    - docker tag $CI_REGISTRY_IMAGE:$CI_IMAGE_TAG $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$CI_IMAGE_TAG

deploy_job:
  stage: deploy
  tags:
    - ec2-runner
  only:
    - feature/ci-cd
  script:
    - echo "Deploying the application..."
    - apk add gettext
    - envsubst < .dev/docker-compose.template.yml > docker-compose.yml
    - scp -i ${SSH_PRIVATE_KEY} docker-compose.yml ${REMOTE_USER}@${REMOTE_HOST}:~
    - ssh -i ${SSH_PRIVATE_KEY} ${REMOTE_USER}@${REMOTE_HOST} 'docker-compose up -d'
  environment:
    name: production
    url: http://${REMOTE_HOST}:8085