package com.sahinokdem.researcher_metadata.enums;

public enum CVAssociation {
    MEMBERSHIPS_AND_AFFILIATIONS,
    RESEARCH_PROJECTS,
    PUBLICATIONS,
    CONFERENCES,
    ACADEMIC_MEMBERSHIPS,
    LABORATORY_EXPERIENCE,
    TECHNICAL_SKILLS,
    RESEARCH_GRANTS_AND_AWARDS,
    MENTORING_AND_TEACHING_EXPERIENCE
}
