version: '3'
services:
  app:
    image: ${CI_REGISTRY_IMAGE}:${CI_IMAGE_TAG}
    container_name: researcher-metadata-management-system
    ports:
      - "8085:8085"
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - SWAGGER_URL=${SWAGGER_URL}
      - STORAGE_PATH=${STORAGE_PATH}
      - SHORT_DAYS=${SHORT_DAYS}
      - LONG_DAYS=${LONG_DAYS}
#    volumes:
#      - app-uploads:${STORAGE_PATH}

#volumes:
#  app-uploads: